### ISSUE TITLE
ConcurrentModificationException in DTDOuput

### ISSUE THREAD

**Issue by GoogleCodeExporter** [qiuwei/jing-trang#16]
```
D:\users\george\workspace\jingOnGoogle\build>java -jar trang.jar -I xml -O
dtd personal.xml personal.dtd
Exception in thread "main" java.util.ConcurrentModificationException
        at
java.util.AbstractList$Itr.checkForComodification(AbstractList.java:449)
        at java.util.AbstractList$Itr.next(AbstractList.java:420)
        at
com.thaiopensource.relaxng.output.dtd.DtdOutput.outputQueuedElements(Unknown 
Source)
        at
com.thaiopensource.relaxng.output.dtd.DtdOutput$GrammarOutput.visitDefine(Unknow
n
Source)
        at
com.thaiopensource.relaxng.output.dtd.DtdOutput$GrammarOutput.visitDefine(Unknow
n
Source)
        at com.thaiopensource.relaxng.edit.DefineComponent.accept(Unknown
Source)
        at
com.thaiopensource.relaxng.output.dtd.DtdOutput$GrammarOutput.visitContainer(Unk
nown
Source)
        at
com.thaiopensource.relaxng.output.dtd.DtdOutput.topLevelOutput(Unknown Source)
        at com.thaiopensource.relaxng.output.dtd.DtdOutput.output(Unknown
Source)
        at
com.thaiopensource.relaxng.output.dtd.DtdOutputFormat.output(Unknown Source)
        at com.thaiopensource.relaxng.translate.Driver.doMain(Unknown Source)
        at com.thaiopensource.relaxng.translate.Driver.main(Unknown Source)


D:\users\george\workspace\jingOnGoogle\build>type personal.xml
<?xml version="1.0" encoding="UTF-8"?>

<personnel>
    <person>
    </person>
</personnel>

```

Original issue reported on code.google.com by `georgebina76` on 22 Oct 2008 at 6:12

**Comment by GoogleCodeExporter** [comment]
Original comment by `jjc.jclark.com` on 22 Oct 2008 at 6:25
- Added labels: **Module-convert-dtd**
- Removed labels: **Module-unknown**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jjc.jclark.com` on 22 Oct 2008 at 6:26
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r2046
```

Original comment by `jjc.jclark.com` on 22 Oct 2008 at 6:44
- Changed state: **Fixed**
- Added labels: **NeedTestCase**

**Comment by GoogleCodeExporter** [comment]
```
Thanks!
```

Original comment by `georgebina76` on 22 Oct 2008 at 7:04
- Changed state: **Verified**
