### ISSUE TITLE
Doubly recursive grammar inference

### ISSUE THREAD

**Issue by GoogleCodeExporter** [qiuwei/jing-trang#79]
```
What steps will reproduce the problem?
1. Create file.xml containing: <a><b><c/></b><c><a/></c></a>
2. java -jar trang.jar file.xml file.rnc

It should output file.rnc quietly (as it does when the XML file is modified
to remove the double dependency between elements a and c, for example using
 <a><b><c/></b><c><d/></c></a>), but instead it throws a Java exception:

Exception in thread "main" java.util.ConcurrentModificationException
        at
java.util.AbstractList$Itr.checkForComodification(AbstractList.java:449)
        at java.util.AbstractList$Itr.next(AbstractList.java:420)
        at com.thaiopensource.relaxng.input.xml.Inferrer.<init>(Unknown Source)
        at com.thaiopensource.relaxng.input.xml.Inferrer.infer(Unknown Source)
        at com.thaiopensource.relaxng.input.xml.XmlInputFormat.load(Unknown
Source)
        at
com.thaiopensource.relaxng.input.AbstractMultiInputFormat.load(Unknown Source)
        at com.thaiopensource.relaxng.translate.Driver.doMain(Unknown Source)
        at com.thaiopensource.relaxng.translate.Driver.main(Unknown Source)

This is with trang 20081028 on Java 1.5.0_13.

PS. I could not confirm that RNC grammars allow double recursion.
```

Original issue reported on code.google.com by `altavox@gmail.com` on 25 May 2009 at 2:40

**Comment by GoogleCodeExporter** [comment]
```
This was fixed in r2307.
Just checkout the head revision and run ant to get the project jars.
```

Original comment by `georgebina76` on 27 May 2009 at 8:14
- Changed state: **Invalid**
- Added labels: **Module-convert-from-xml**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jjc.jclark.com` on 27 May 2009 at 8:49
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
How do I download the new version of trang.jar with this bug fixed?
isidora@juno.com

```

Original comment by `izzybit...@gmail.com` on 10 Jun 2009 at 6:56

**Comment by GoogleCodeExporter** [comment]
```
See my previous comment - you can get the jars by checking out the sources and
running the ant script to build the jars. If you have difficulties let me know 
and I
will upload it.
```

Original comment by `georgebina76` on 11 Jun 2009 at 3:07

**Comment by GoogleCodeExporter** [comment]
```
Could you please upload it? I need to get this fix today and unfortunately I 
have no
svn installed yet on my PC. Thks (izzybitsie)
```

Original comment by `izzybit...@gmail.com` on 11 Jun 2009 at 6:03

**Comment by GoogleCodeExporter** [comment]
```
You can find the current jing-tang jars here

http://www.oxygenxml.com/update/jing.jar
http://www.oxygenxml.com/update/trang.jar

NOTE: The above URLs will be available only for a couple of weeks.
```

Original comment by `georgebina76` on 12 Jun 2009 at 2:50
